---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Dealer Portal:
    - Dev:
        href: https://dealer.chektdev.com/
    - QE:
        href: https://dealer.chektqe.com/
    - S1:
        href: https://dealer-s1.chekt.com/
    - Prod:
        href: https://dealer.chekt.com/
        # ping: https://dealer.chekt.com/

- Monitoring Portal:
    - Dev:
        href: https://monitoring.chektdev.com/
    - QE:
        href: https://monitoring.chektqe.com/
    - S1:
        href: https://monitoring-s1.chekt.com/
    - Prod:
        href: https://monitoring.chekt.com/

- End User Web:
    - Dev:
        href: https://app.chektdev.com/
    - QE:
        href: https://app.chektqe.com/
    - S1:
        href: https://app-s1.chekt.com/
    - Prod:
        href: https://app.chekt.com/

- Console:
    - Dev:
        href: https://console.chektdev.com/
    - QE:
        href: https://console.chektqe.com/
    - S1:
        href: https://console-s1.chekt.com/
    - Prod:
        href: https://console.chekt.com/

- Account:
    - Dev:
        href: https://account.chektdev.com/
    - QE:
        href: https://account.chektqe.com/
    - S1:
        href: https://account-s1.chekt.com/
    - Prod:
        href: https://account.chekt.com/

- Tools:
    - AWS:
        icon: /icons/aws.svg
        href: https://console.aws.amazon.com
    - GCP:
        icon: /icons/gcp.svg
        href: https://console.cloud.google.com
    - Digital Ocean:
        icon: /icons/digitalocean.svg
        href: https://cloud.digitalocean.com
    - GitHub:
        icon: /icons/github.svg
        href: https://github.com/chekt
    - Jira:
        icon: /icons/jira.svg
        href: https://alarmcom.atlassian.net/jira/software/c/projects/CHEKT/boards/232?quickFilter=529
    - Codefresh:
        icon: /icons/codefresh.png
        href: https://g.codefresh.io
    - Keycloak:
        icon: /icons/keycloak.svg
        href: https://keycloak.chektdev.com
    - Status:
        icon: /icons/status.png
        href: https://status.chekt.com
    - Auth0:
        icon: /icons/auth0.svg
        href: https://manage.auth0.com/dashboard
    - Twilio:
        icon: /icons/twilio.png
        href: https://console.twilio.com/
    - Firebase:
        icon: /icons/firebase.svg
        href: https://console.firebase.google.com
    - Figma:
        icon: /icons/figma.svg
        href: https://www.figma.com/files/1040663912643495126/team/933301007274602444/CHeKT?fuid=1539269208954171621
    - Sentry:
        icon: /icons/sentry.png
        href: https://chekt.sentry.io/issues
    - Notion:
        icon: /icons/notion.svg
        href: https://www.notion.so/chekt
    - Zoho:
        icon: /icons/zoho.png
        href: https://www.zoho.com/
        description: 링크를 몰라요
    - Calipsa:
        icon: /icons/calipsa.png
        href: https://calipsa.com
        description: 링크를 몰라요
    - Actuate:
        icon: /icons/actuate.png
        href: https://actuate.com
        description: 링크를 몰라요
- Tools(By Env):
    - Kibana:
        - Dev:
            icon: /icons/kibana.svg
            href: https://kibana.chektdev.com
        - QE:
            icon: /icons/kibana.svg
            href: https://kibana.chektqe.com
        - Prod:
            icon: /icons/kibana.svg
            href: https://kibana.chekt.com
    - Grafana:
        - Dev:
            icon: grafana.png
            href: https://grafana.chektdev.com/
        - QE:
            icon: grafana.png
            href: https://grafana.chektqe.com/
        - Prod:
            icon: grafana.png
            href: https://grafana.chekt.com/
    - GitOps:
        - Dev:
            icon: /icons/argocd.svg
            href: https://gitops.chektdev.com
        - QE:
            icon: /icons/argocd.svg
            href: https://gitops.chektqe.com
        - Prod:
            icon: /icons/argocd.svg
            href: https://gitops.chekt.com
- Misc:
    - World Time Buddy:
        icon: /icons/world-time-buddy.png
        href: https://www.worldtimebuddy.com/
        description: 시차 계산기
    - CHeKT Bot:
        icon: /icons/slack.svg
        href: https://api.slack.com/apps/A09DUJP9RFA
        description: Ask Jeff to be a collaborator


# ADC
- ADC:
    - Okta:
        icon: /icons/okta.svg
        href: https://alarm.okta.com/app
        description: 인증 서비스
    - Navan:
        icon: /icons/navan.png
        href: https://alarm.okta.com/home/tripactions/0oa1o7y4xayWsHR5h0h8/aln1g73qivtpePS791d8
        description: 항공권 예약
    - Workday:
        icon: /icons/workday.png
        href: https://alarm.okta.com/home/workday/0oa1al5utnkIzB3ex0h8/30
        description: 정확히 뭘까 이건
    - Deel:
        icon: /icons/deel.png
        href: https://app.deel.com/
        description: 급여, 휴가 관리
    - WIZ:
        icon: /icons/wiz.svg
        href: https://app.wiz.io
        description: 클라우드 보안
    - Spam Quarantine:
        icon: /icons/spam.png
        href: https://dh4926-euq1.iphmx.com/
        description: 스팸 메일함
    - ServiceNow:
        icon: /icons/servicenow.png
        href: https://alarmprod.service-now.com/adc_ec
        description: 문의사항
    - Expensify:
        icon: /icons/expensify.png
        href: https://www.expensify.com
        description: 경비 청구
    - ChatADC:
        icon: /icons/chatadc.png
        href: https://chatadc.com/
        description: ChatGPT
    # - Secret Server:
    #     icon: /icons/secret-server.png
    #     href: https://secret.chekt.com
    #     description: 비밀번호 관리